### ISSUE TITLE
EJDBTest fails

### ISSUE THREAD

**Issue by echox** [Softmotions/ejdb-java#3]
During build the jar file is generated successfully but the EJDBTest seems to be broken:
```
    [junit] Running org.ejdb.driver.test.EJDBQueryBuilderTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec
    [junit] Running org.ejdb.driver.test.EJDBTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 sec

BUILD FAILED
/Users/foo/Documents/workspace/db/build.xml:116: The following error occurred while executing this line:
/Users/foo/Documents/workspace/db/build.xml:60: Test org.ejdb.driver.test.EJDBTest failed

Total time: 2 seconds
make: *** [jejdb] Error 1
```

I was not able to get the tests running in my IDE to supply more details.

**Comment by obourdon** [comment]
In my clone of the ejdb-java git repo, you'll find a version which is currently working for Linuxes and MacOSX
Hope this helps
Best regards

**Comment by echox** [comment]
Thanks!!! This does not only fix the build problems, it also fixes my problem I posted on stackoverf.. ah thats how you came here :-) (http://stackoverflow.com/questions/28728126/ejdb-java-binding-not-working-no-jejdb-in-java-library-path) Should be merged back :-)
:+1:

**Comment by obourdon** [comment]
Thanks a lot for your feedback, I have just submitted the pull request. Best regards

**Comment by dalegaspi** [comment]
~~I'm on OS X Yosemite and trying to build this project  I'm getting this error:~~

```
configure: error: tcejdb/ejdb.h is required
```

~~I have built the ejdb C libraries successfully and have success in running the ejdb CLI (node.js) which means the libraries are fine.  i did notice that when the ejdb C libraries are built and installed, the headers are installed in `ejdb/ejdb.h` instead of `tecejdb/ejdb.h` ... i tried to change the configure script to reference those headers instead, but I'm getting errors in make due to unsatisfied link errors.~~ 

~~This can't be this complicated...any help is appreciated...I wish this was just a simple Maven reference. :-(~~

_You need to make sure that you have the Latest JDK installed (1.8.0_45 for JDK8 as of this writing) to build the project successfully._
